package http

import (
	"encoding/json"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5"

	"github.com/XoDeR/empops/api-go/pkg/companyauth"
	"github.com/XoDeR/empops/api-go/pkg/response"
	"github.com/XoDeR/empops/api-go/pkg/uuidv7"
)

func (h *Handler) ListAMASessions(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());rows,err:=h.pool.Query(r.Context(),`SELECT s.id,s.happened_at,s.active,s.theme,s.created_at,count(q.id) FROM ask_me_anything_sessions s LEFT JOIN ask_me_anything_questions q ON q.ask_me_anything_session_id=s.id WHERE s.company_id=$1 GROUP BY s.id ORDER BY s.happened_at DESC`,m.CompanyID);if err!=nil{response.Fail(w,500,"list AMA sessions failed",err.Error());return};defer rows.Close();out:=[]map[string]interface{}{};for rows.Next(){var id string;var happened,created time.Time;var active bool;var theme *string;var count int;if rows.Scan(&id,&happened,&active,&theme,&created,&count)==nil{out=append(out,map[string]interface{}{"id":id,"company_id":m.CompanyID,"happened_at":happened.Format("2006-01-02"),"active":active,"theme":theme,"questions_count":count,"created_at":created.UTC().Format(time.RFC3339)})}};response.OK(w,"",out)}
type amaSessionRequest struct{HappenedAt string `json:"happened_at"`;Active *bool `json:"active"`;Theme *string `json:"theme"`}
func (h *Handler) CreateAMASession(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var req amaSessionRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil{response.Fail(w,400,"Invalid JSON body",nil);return};day,err:=time.Parse("2006-01-02",req.HappenedAt);if err!=nil{response.Fail(w,422,"happened_at is required",nil);return};active:=false;if req.Active!=nil{active=*req.Active};id:=uuidv7.New();tx,err:=h.pool.Begin(r.Context());if err!=nil{response.Fail(w,500,"transaction failed",err.Error());return};defer tx.Rollback(r.Context());if active{_,_=tx.Exec(r.Context(),`UPDATE ask_me_anything_sessions SET active=false,updated_at=now() WHERE company_id=$1`,m.CompanyID)};_,err=tx.Exec(r.Context(),`INSERT INTO ask_me_anything_sessions(id,company_id,happened_at,active,theme) VALUES($1,$2,$3,$4,$5)`,id,m.CompanyID,day,active,req.Theme);if err!=nil{response.Fail(w,500,"create AMA session failed",err.Error());return};if err=tx.Commit(r.Context());err!=nil{response.Fail(w,500,"commit failed",err.Error());return};response.Created(w,"AMA session created",map[string]interface{}{"id":id,"company_id":m.CompanyID,"happened_at":req.HappenedAt,"active":active,"theme":req.Theme})}
func (h *Handler) ShowAMASession(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());id:=chi.URLParam(r,"sessionId");var happened time.Time;var active bool;var theme *string;if err:=h.pool.QueryRow(r.Context(),`SELECT happened_at,active,theme FROM ask_me_anything_sessions WHERE id=$1 AND company_id=$2`,id,m.CompanyID).Scan(&happened,&active,&theme);err==pgx.ErrNoRows{response.Fail(w,404,"AMA session not found",nil);return}else if err!=nil{response.Fail(w,500,"session lookup failed",err.Error());return};questions,err:=h.amaQuestions(r,id);if err!=nil{response.Fail(w,500,"list questions failed",err.Error());return};response.OK(w,"",map[string]interface{}{"id":id,"company_id":m.CompanyID,"happened_at":happened.Format("2006-01-02"),"active":active,"theme":theme,"questions":questions})}
func (h *Handler) UpdateAMASession(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var req amaSessionRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil{response.Fail(w,400,"Invalid JSON body",nil);return};id:=chi.URLParam(r,"sessionId");if req.HappenedAt!=""{if day,err:=time.Parse("2006-01-02",req.HappenedAt);err==nil{_,_=h.pool.Exec(r.Context(),`UPDATE ask_me_anything_sessions SET happened_at=$1,updated_at=now() WHERE id=$2 AND company_id=$3`,day,id,m.CompanyID)}};if req.Theme!=nil{_,_=h.pool.Exec(r.Context(),`UPDATE ask_me_anything_sessions SET theme=$1,updated_at=now() WHERE id=$2 AND company_id=$3`,req.Theme,id,m.CompanyID)};if req.Active!=nil{if *req.Active{_,_=h.pool.Exec(r.Context(),`UPDATE ask_me_anything_sessions SET active=false,updated_at=now() WHERE company_id=$1`,m.CompanyID)};_,_=h.pool.Exec(r.Context(),`UPDATE ask_me_anything_sessions SET active=$1,updated_at=now() WHERE id=$2 AND company_id=$3`,*req.Active,id,m.CompanyID)};h.ShowAMASession(w,r)}
func (h *Handler) DeleteAMASession(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());tag,err:=h.pool.Exec(r.Context(),`DELETE FROM ask_me_anything_sessions WHERE id=$1 AND company_id=$2`,chi.URLParam(r,"sessionId"),m.CompanyID);writeDeleted(w,tag.RowsAffected(),err,"AMA session")}
func (h *Handler) ListAMAQuestions(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var exists bool;_ = h.pool.QueryRow(r.Context(),`SELECT EXISTS(SELECT 1 FROM ask_me_anything_sessions WHERE id=$1 AND company_id=$2)`,chi.URLParam(r,"sessionId"),m.CompanyID).Scan(&exists);if !exists{response.Fail(w,404,"AMA session not found",nil);return};out,err:=h.amaQuestions(r,chi.URLParam(r,"sessionId"));if err!=nil{response.Fail(w,500,"list questions failed",err.Error());return};response.OK(w,"",out)}
func (h *Handler) CreateAMAQuestion(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var req struct{Question string `json:"question"`;Anonymous bool `json:"anonymous"`};if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Question)==""{response.Fail(w,422,"question is required",nil);return};id:=uuidv7.New();tag,err:=h.pool.Exec(r.Context(),`INSERT INTO ask_me_anything_questions(id,ask_me_anything_session_id,employee_id,question,anonymous) SELECT $1,s.id,$2,$3,$4 FROM ask_me_anything_sessions s WHERE s.id=$5 AND s.company_id=$6`,id,m.EmployeeID,strings.TrimSpace(req.Question),req.Anonymous,chi.URLParam(r,"sessionId"),m.CompanyID);if err!=nil{response.Fail(w,500,"create question failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"AMA session not found",nil);return};response.Created(w,"AMA question created",map[string]interface{}{"id":id,"question":req.Question,"answered":false,"anonymous":req.Anonymous})}
func (h *Handler) UpdateAMAQuestion(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var req struct{Question *string `json:"question"`;Answered *bool `json:"answered"`;Anonymous *bool `json:"anonymous"`};if json.NewDecoder(r.Body).Decode(&req)!=nil{response.Fail(w,400,"Invalid JSON body",nil);return};id:=chi.URLParam(r,"questionId");if req.Question!=nil&&strings.TrimSpace(*req.Question)!=""{_,_=h.pool.Exec(r.Context(),`UPDATE ask_me_anything_questions q SET question=$1,updated_at=now() FROM ask_me_anything_sessions s WHERE q.id=$2 AND q.ask_me_anything_session_id=s.id AND s.company_id=$3`,strings.TrimSpace(*req.Question),id,m.CompanyID)};if req.Answered!=nil{_,_=h.pool.Exec(r.Context(),`UPDATE ask_me_anything_questions q SET answered=$1,updated_at=now() FROM ask_me_anything_sessions s WHERE q.id=$2 AND q.ask_me_anything_session_id=s.id AND s.company_id=$3`,*req.Answered,id,m.CompanyID)};if req.Anonymous!=nil{_,_=h.pool.Exec(r.Context(),`UPDATE ask_me_anything_questions q SET anonymous=$1,updated_at=now() FROM ask_me_anything_sessions s WHERE q.id=$2 AND q.ask_me_anything_session_id=s.id AND s.company_id=$3`,*req.Anonymous,id,m.CompanyID)};response.OK(w,"AMA question updated",map[string]interface{}{"id":id})}
func (h *Handler) DeleteAMAQuestion(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());tag,err:=h.pool.Exec(r.Context(),`DELETE FROM ask_me_anything_questions q USING ask_me_anything_sessions s WHERE q.id=$1 AND q.ask_me_anything_session_id=s.id AND s.company_id=$2`,chi.URLParam(r,"questionId"),m.CompanyID);writeDeleted(w,tag.RowsAffected(),err,"AMA question")}
func(h *Handler)amaQuestions(r *http.Request,sessionID string)([]map[string]interface{},error){rows,err:=h.pool.Query(r.Context(),`SELECT q.id,q.employee_id,q.question,q.answered,q.anonymous,q.created_at,trim(e.first_name||' '||e.last_name) FROM ask_me_anything_questions q LEFT JOIN employees e ON e.id=q.employee_id WHERE q.ask_me_anything_session_id=$1 ORDER BY q.created_at`,sessionID);if err!=nil{return nil,err};defer rows.Close();out:=[]map[string]interface{}{};for rows.Next(){var id,question string;var employeeID,name *string;var answered,anonymous bool;var created time.Time;if err:=rows.Scan(&id,&employeeID,&question,&answered,&anonymous,&created,&name);err!=nil{return nil,err};var author interface{}=name;if anonymous{author=nil;employeeID=nil};out=append(out,map[string]interface{}{"id":id,"employee_id":employeeID,"employee_name":author,"question":question,"answered":answered,"anonymous":anonymous,"created_at":created.UTC().Format(time.RFC3339)})};return out,nil}
