package http

import (
	"encoding/json"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5"

	"github.com/XoDeR/empops/api-go/pkg/companyauth"
	"github.com/XoDeR/empops/api-go/pkg/response"
	"github.com/XoDeR/empops/api-go/pkg/uuidv7"
)

func (h *Handler) ListWikis(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());rows,err:=h.pool.Query(r.Context(),`SELECT w.id,w.title,w.created_at,count(p.id) FROM wikis w LEFT JOIN wiki_pages p ON p.wiki_id=w.id WHERE w.company_id=$1 GROUP BY w.id ORDER BY w.title`,m.CompanyID);if err!=nil{response.Fail(w,500,"list wikis failed",err.Error());return};defer rows.Close();out:=[]map[string]interface{}{};for rows.Next(){var id,title string;var created time.Time;var count int;if rows.Scan(&id,&title,&created,&count)==nil{out=append(out,map[string]interface{}{"id":id,"company_id":m.CompanyID,"title":title,"pages_count":count,"created_at":created.UTC().Format(time.RFC3339)})}};response.OK(w,"",out)}
func (h *Handler) CreateWiki(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var req struct{Title string `json:"title"`};if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Title)==""{response.Fail(w,422,"title is required",nil);return};id:=uuidv7.New();_,err:=h.pool.Exec(r.Context(),`INSERT INTO wikis(id,company_id,title) VALUES($1,$2,$3)`,id,m.CompanyID,strings.TrimSpace(req.Title));if err!=nil{response.Fail(w,500,"create wiki failed",err.Error());return};response.Created(w,"Wiki created",map[string]interface{}{"id":id,"company_id":m.CompanyID,"title":req.Title})}
func (h *Handler) ShowWiki(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());id:=chi.URLParam(r,"wikiId");var title string;if err:=h.pool.QueryRow(r.Context(),`SELECT title FROM wikis WHERE id=$1 AND company_id=$2`,id,m.CompanyID).Scan(&title);err==pgx.ErrNoRows{response.Fail(w,404,"Wiki not found",nil);return}else if err!=nil{response.Fail(w,500,"wiki lookup failed",err.Error());return};rows,err:=h.pool.Query(r.Context(),`SELECT id,title,content,pageviews_counter,created_at,updated_at FROM wiki_pages WHERE wiki_id=$1 ORDER BY title`,id);if err!=nil{response.Fail(w,500,"list pages failed",err.Error());return};defer rows.Close();pages:=[]map[string]interface{}{};for rows.Next(){item,e:=scanWikiPage(rows);if e==nil{pages=append(pages,item)}};response.OK(w,"",map[string]interface{}{"id":id,"company_id":m.CompanyID,"title":title,"pages":pages})}
func (h *Handler) UpdateWiki(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var req struct{Title string `json:"title"`};if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Title)==""{response.Fail(w,422,"title is required",nil);return};tag,err:=h.pool.Exec(r.Context(),`UPDATE wikis SET title=$1,updated_at=now() WHERE id=$2 AND company_id=$3`,strings.TrimSpace(req.Title),chi.URLParam(r,"wikiId"),m.CompanyID);if err!=nil{response.Fail(w,500,"update wiki failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Wiki not found",nil);return};response.OK(w,"Wiki updated",map[string]interface{}{"id":chi.URLParam(r,"wikiId"),"title":req.Title})}
func (h *Handler) DeleteWiki(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());tag,err:=h.pool.Exec(r.Context(),`DELETE FROM wikis WHERE id=$1 AND company_id=$2`,chi.URLParam(r,"wikiId"),m.CompanyID);writeDeleted(w,tag.RowsAffected(),err,"Wiki")}

type wikiPageRequest struct{Title string `json:"title"`;Content *string `json:"content"`}
func (h *Handler) CreateWikiPage(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var req wikiPageRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Title)==""{response.Fail(w,422,"title is required",nil);return};id:=uuidv7.New();tag,err:=h.pool.Exec(r.Context(),`INSERT INTO wiki_pages(id,wiki_id,title,content) SELECT $1,w.id,$2,$3 FROM wikis w WHERE w.id=$4 AND w.company_id=$5`,id,strings.TrimSpace(req.Title),req.Content,chi.URLParam(r,"wikiId"),m.CompanyID);if err!=nil{response.Fail(w,500,"create page failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Wiki not found",nil);return};h.saveWikiRevision(r,id,req.Title,req.Content);response.Created(w,"Wiki page created",map[string]interface{}{"id":id,"wiki_id":chi.URLParam(r,"wikiId"),"title":req.Title,"content":req.Content,"pageviews_counter":0})}
func (h *Handler) ShowWikiPage(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());item,err:=scanWikiPage(h.pool.QueryRow(r.Context(),`UPDATE wiki_pages p SET pageviews_counter=pageviews_counter+1 FROM wikis w WHERE p.id=$1 AND p.wiki_id=w.id AND w.id=$2 AND w.company_id=$3 RETURNING p.id,p.title,p.content,p.pageviews_counter,p.created_at,p.updated_at`,chi.URLParam(r,"pageId"),chi.URLParam(r,"wikiId"),m.CompanyID));if err==pgx.ErrNoRows{response.Fail(w,404,"Wiki page not found",nil);return};if err!=nil{response.Fail(w,500,"page lookup failed",err.Error());return};response.OK(w,"",item)}
func (h *Handler) UpdateWikiPage(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());var req wikiPageRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Title)==""{response.Fail(w,422,"title is required",nil);return};id:=chi.URLParam(r,"pageId");tag,err:=h.pool.Exec(r.Context(),`UPDATE wiki_pages p SET title=$1,content=$2,updated_at=now() FROM wikis w WHERE p.id=$3 AND p.wiki_id=w.id AND w.id=$4 AND w.company_id=$5`,strings.TrimSpace(req.Title),req.Content,id,chi.URLParam(r,"wikiId"),m.CompanyID);if err!=nil{response.Fail(w,500,"update page failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Wiki page not found",nil);return};h.saveWikiRevision(r,id,req.Title,req.Content);response.OK(w,"Wiki page updated",map[string]interface{}{"id":id,"title":req.Title,"content":req.Content})}
func (h *Handler) DeleteWikiPage(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());tag,err:=h.pool.Exec(r.Context(),`DELETE FROM wiki_pages p USING wikis w WHERE p.id=$1 AND p.wiki_id=w.id AND w.id=$2 AND w.company_id=$3`,chi.URLParam(r,"pageId"),chi.URLParam(r,"wikiId"),m.CompanyID);writeDeleted(w,tag.RowsAffected(),err,"Wiki page")}
func (h *Handler) ListWikiPageRevisions(w http.ResponseWriter,r *http.Request){m,_:=companyauth.MemberFromContext(r.Context());rows,err:=h.pool.Query(r.Context(),`SELECT rv.id,rv.employee_id,rv.employee_name,rv.title,rv.content,rv.created_at FROM wiki_page_revisions rv JOIN wiki_pages p ON p.id=rv.page_id JOIN wikis w ON w.id=p.wiki_id WHERE rv.page_id=$1 AND w.id=$2 AND w.company_id=$3 ORDER BY rv.created_at DESC`,chi.URLParam(r,"pageId"),chi.URLParam(r,"wikiId"),m.CompanyID);if err!=nil{response.Fail(w,500,"list revisions failed",err.Error());return};defer rows.Close();out:=[]map[string]interface{}{};for rows.Next(){var id,name,title string;var employeeID,content *string;var created time.Time;if rows.Scan(&id,&employeeID,&name,&title,&content,&created)==nil{out=append(out,map[string]interface{}{"id":id,"employee_id":employeeID,"employee_name":name,"title":title,"content":content,"created_at":created.UTC().Format(time.RFC3339)})}};response.OK(w,"",out)}

func(h *Handler)saveWikiRevision(r *http.Request,pageID,title string,content *string){m,_:=companyauth.MemberFromContext(r.Context());name:="Unknown";_ = h.pool.QueryRow(r.Context(),`SELECT trim(first_name||' '||last_name) FROM employees WHERE id=$1`,m.EmployeeID).Scan(&name);_,_=h.pool.Exec(r.Context(),`INSERT INTO wiki_page_revisions(id,page_id,employee_id,employee_name,title,content) VALUES($1,$2,$3,$4,$5,$6)`,uuidv7.New(),pageID,m.EmployeeID,name,title,content)}
func scanWikiPage(row pgx.Row)(map[string]interface{},error){var id,title string;var content *string;var views int;var created,updated time.Time;if err:=row.Scan(&id,&title,&content,&views,&created,&updated);err!=nil{return nil,err};return map[string]interface{}{"id":id,"title":title,"content":content,"pageviews_counter":views,"created_at":created.UTC().Format(time.RFC3339),"updated_at":updated.UTC().Format(time.RFC3339)},nil}
