package http

import (
	"encoding/json"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/XoDeR/empops/api-go/pkg/companyauth"
	"github.com/XoDeR/empops/api-go/pkg/response"
	"github.com/XoDeR/empops/api-go/pkg/uuidv7"
)

type Handler struct{pool *pgxpool.Pool}
func NewHandler(pool *pgxpool.Pool)*Handler{return &Handler{pool:pool}}
func member(r *http.Request)companyauth.Member{m,_:=companyauth.MemberFromContext(r.Context());return m}
func deleted(w http.ResponseWriter,rows int64,err error,name string){if err!=nil{response.Fail(w,500,"delete failed",err.Error());return};if rows==0{response.Fail(w,404,name+" not found",nil);return};response.OK(w,name+" deleted",nil)}

func(h *Handler)ListGroups(w http.ResponseWriter,r *http.Request){m:=member(r);rows,err:=h.pool.Query(r.Context(),`SELECT g.id,g.name,g.mission,g.created_at,count(eg.employee_id) FROM groups g LEFT JOIN employee_group eg ON eg.group_id=g.id WHERE g.company_id=$1 GROUP BY g.id ORDER BY g.name`,m.CompanyID);if err!=nil{response.Fail(w,500,"list groups failed",err.Error());return};defer rows.Close();out:=[]map[string]interface{}{};for rows.Next(){var id,name string;var mission *string;var created time.Time;var count int;if rows.Scan(&id,&name,&mission,&created,&count)==nil{out=append(out,map[string]interface{}{"id":id,"company_id":m.CompanyID,"name":name,"mission":mission,"members_count":count,"created_at":created.UTC().Format(time.RFC3339)})}};response.OK(w,"",out)}
type groupRequest struct{Name string `json:"name"`;Mission *string `json:"mission"`}
func(h *Handler)CreateGroup(w http.ResponseWriter,r *http.Request){m:=member(r);var req groupRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Name)==""{response.Fail(w,422,"name is required",nil);return};id:=uuidv7.New();_,err:=h.pool.Exec(r.Context(),`INSERT INTO groups(id,company_id,name,mission) VALUES($1,$2,$3,$4)`,id,m.CompanyID,strings.TrimSpace(req.Name),req.Mission);if err!=nil{response.Fail(w,500,"create group failed",err.Error());return};response.Created(w,"Group created",map[string]interface{}{"id":id,"company_id":m.CompanyID,"name":req.Name,"mission":req.Mission})}
func(h *Handler)ShowGroup(w http.ResponseWriter,r *http.Request){m:=member(r);id:=chi.URLParam(r,"groupId");var name string;var mission *string;if err:=h.pool.QueryRow(r.Context(),`SELECT name,mission FROM groups WHERE id=$1 AND company_id=$2`,id,m.CompanyID).Scan(&name,&mission);err==pgx.ErrNoRows{response.Fail(w,404,"Group not found",nil);return}else if err!=nil{response.Fail(w,500,"group lookup failed",err.Error());return};rows,err:=h.pool.Query(r.Context(),`SELECT e.id,e.first_name,e.last_name,e.email FROM employee_group eg JOIN employees e ON e.id=eg.employee_id WHERE eg.group_id=$1 ORDER BY e.first_name,e.last_name`,id);if err!=nil{response.Fail(w,500,"list members failed",err.Error());return};defer rows.Close();members:=[]map[string]interface{}{};for rows.Next(){var eid,first,last,email string;if rows.Scan(&eid,&first,&last,&email)==nil{members=append(members,map[string]interface{}{"id":eid,"first_name":first,"last_name":last,"email":email})}};response.OK(w,"",map[string]interface{}{"id":id,"company_id":m.CompanyID,"name":name,"mission":mission,"members":members})}
func(h *Handler)UpdateGroup(w http.ResponseWriter,r *http.Request){m:=member(r);var req groupRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Name)==""{response.Fail(w,422,"name is required",nil);return};tag,err:=h.pool.Exec(r.Context(),`UPDATE groups SET name=$1,mission=$2,updated_at=now() WHERE id=$3 AND company_id=$4`,strings.TrimSpace(req.Name),req.Mission,chi.URLParam(r,"groupId"),m.CompanyID);if err!=nil{response.Fail(w,500,"update group failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Group not found",nil);return};response.OK(w,"Group updated",map[string]interface{}{"id":chi.URLParam(r,"groupId"),"name":req.Name,"mission":req.Mission})}
func(h *Handler)DeleteGroup(w http.ResponseWriter,r *http.Request){m:=member(r);tag,err:=h.pool.Exec(r.Context(),`DELETE FROM groups WHERE id=$1 AND company_id=$2`,chi.URLParam(r,"groupId"),m.CompanyID);deleted(w,tag.RowsAffected(),err,"Group")}
func(h *Handler)AddMember(w http.ResponseWriter,r *http.Request){m:=member(r);employeeID:=chi.URLParam(r,"employeeId");if employeeID==""{response.Fail(w,422,"employee_id is required",nil);return};tag,err:=h.pool.Exec(r.Context(),`INSERT INTO employee_group(employee_id,group_id) SELECT e.id,g.id FROM employees e JOIN groups g ON g.company_id=e.company_id WHERE e.id=$1 AND g.id=$2 AND g.company_id=$3 ON CONFLICT DO NOTHING`,employeeID,chi.URLParam(r,"groupId"),m.CompanyID);if err!=nil{response.Fail(w,500,"add member failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Group or employee not found",nil);return};response.Created(w,"Member added",map[string]interface{}{"employee_id":employeeID})}
func(h *Handler)RemoveMember(w http.ResponseWriter,r *http.Request){m:=member(r);tag,err:=h.pool.Exec(r.Context(),`DELETE FROM employee_group eg USING groups g WHERE eg.employee_id=$1 AND eg.group_id=g.id AND g.id=$2 AND g.company_id=$3`,chi.URLParam(r,"employeeId"),chi.URLParam(r,"groupId"),m.CompanyID);deleted(w,tag.RowsAffected(),err,"Group member")}

type meetingRequest struct{Happened bool `json:"happened"`;HappenedAt *string `json:"happened_at"`}
func(h *Handler)ListMeetings(w http.ResponseWriter,r *http.Request){m:=member(r);rows,err:=h.pool.Query(r.Context(),`SELECT mt.id,mt.happened,mt.happened_at,mt.created_at FROM meetings mt JOIN groups g ON g.id=mt.group_id WHERE g.id=$1 AND g.company_id=$2 ORDER BY mt.happened_at DESC NULLS FIRST,mt.created_at DESC`,chi.URLParam(r,"groupId"),m.CompanyID);if err!=nil{response.Fail(w,500,"list meetings failed",err.Error());return};defer rows.Close();out:=[]map[string]interface{}{};for rows.Next(){var id string;var happened bool;var happenedAt *time.Time;var created time.Time;if rows.Scan(&id,&happened,&happenedAt,&created)==nil{out=append(out,meetingPayload(id,chi.URLParam(r,"groupId"),happened,happenedAt,created))}};response.OK(w,"",out)}
func(h *Handler)CreateMeeting(w http.ResponseWriter,r *http.Request){m:=member(r);var req meetingRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil{response.Fail(w,400,"Invalid JSON body",nil);return};day,ok:=parseDate(req.HappenedAt);if !ok{response.Fail(w,422,"invalid happened_at",nil);return};id:=uuidv7.New();tag,err:=h.pool.Exec(r.Context(),`INSERT INTO meetings(id,group_id,happened,happened_at) SELECT $1,g.id,$2,$3 FROM groups g WHERE g.id=$4 AND g.company_id=$5`,id,req.Happened,day,chi.URLParam(r,"groupId"),m.CompanyID);if err!=nil{response.Fail(w,500,"create meeting failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Group not found",nil);return};response.Created(w,"Meeting created",meetingPayload(id,chi.URLParam(r,"groupId"),req.Happened,day,time.Now()))}
func(h *Handler)ShowMeeting(w http.ResponseWriter,r *http.Request){m:=member(r);id:=chi.URLParam(r,"meetingId");var happened bool;var happenedAt *time.Time;var created time.Time;if err:=h.pool.QueryRow(r.Context(),`SELECT mt.happened,mt.happened_at,mt.created_at FROM meetings mt JOIN groups g ON g.id=mt.group_id WHERE mt.id=$1 AND g.id=$2 AND g.company_id=$3`,id,chi.URLParam(r,"groupId"),m.CompanyID).Scan(&happened,&happenedAt,&created);err==pgx.ErrNoRows{response.Fail(w,404,"Meeting not found",nil);return}else if err!=nil{response.Fail(w,500,"meeting lookup failed",err.Error());return};attendees,_:=h.attendees(r,id);agenda,_:=h.agenda(r,id);p:=meetingPayload(id,chi.URLParam(r,"groupId"),happened,happenedAt,created);p["attendees"]=attendees;p["agenda_items"]=agenda;response.OK(w,"",p)}
func(h *Handler)UpdateMeeting(w http.ResponseWriter,r *http.Request){m:=member(r);var req meetingRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil{response.Fail(w,400,"Invalid JSON body",nil);return};day,ok:=parseDate(req.HappenedAt);if !ok{response.Fail(w,422,"invalid happened_at",nil);return};tag,err:=h.pool.Exec(r.Context(),`UPDATE meetings mt SET happened=$1,happened_at=$2,updated_at=now() FROM groups g WHERE mt.id=$3 AND mt.group_id=g.id AND g.id=$4 AND g.company_id=$5`,req.Happened,day,chi.URLParam(r,"meetingId"),chi.URLParam(r,"groupId"),m.CompanyID);if err!=nil{response.Fail(w,500,"update meeting failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Meeting not found",nil);return};response.OK(w,"Meeting updated",nil)}
func(h *Handler)DeleteMeeting(w http.ResponseWriter,r *http.Request){m:=member(r);tag,err:=h.pool.Exec(r.Context(),`DELETE FROM meetings mt USING groups g WHERE mt.id=$1 AND mt.group_id=g.id AND g.company_id=$2`,chi.URLParam(r,"meetingId"),m.CompanyID);deleted(w,tag.RowsAffected(),err,"Meeting")}
func(h *Handler)AddAttendee(w http.ResponseWriter,r *http.Request){m:=member(r);var req struct{EmployeeID string `json:"employee_id"`;WasAGuest bool `json:"was_a_guest"`;Attended bool `json:"attended"`};if json.NewDecoder(r.Body).Decode(&req)!=nil||req.EmployeeID==""{response.Fail(w,422,"employee_id is required",nil);return};tag,err:=h.pool.Exec(r.Context(),`INSERT INTO employee_meeting(employee_id,meeting_id,was_a_guest,attended) SELECT e.id,mt.id,$1,$2 FROM employees e JOIN groups g ON g.company_id=e.company_id JOIN meetings mt ON mt.group_id=g.id WHERE e.id=$3 AND mt.id=$4 AND g.company_id=$5 ON CONFLICT(employee_id,meeting_id) DO UPDATE SET was_a_guest=EXCLUDED.was_a_guest,attended=EXCLUDED.attended,updated_at=now()`,req.WasAGuest,req.Attended,req.EmployeeID,chi.URLParam(r,"meetingId"),m.CompanyID);if err!=nil{response.Fail(w,500,"add attendee failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Meeting or employee not found",nil);return};response.OK(w,"Attendee saved",map[string]interface{}{"employee_id":req.EmployeeID,"was_a_guest":req.WasAGuest,"attended":req.Attended})}
func(h *Handler)RemoveAttendee(w http.ResponseWriter,r *http.Request){m:=member(r);tag,err:=h.pool.Exec(r.Context(),`DELETE FROM employee_meeting em USING meetings mt,groups g WHERE em.employee_id=$1 AND em.meeting_id=mt.id AND mt.id=$2 AND mt.group_id=g.id AND g.company_id=$3`,chi.URLParam(r,"employeeId"),chi.URLParam(r,"meetingId"),m.CompanyID);deleted(w,tag.RowsAffected(),err,"Attendee")}

type agendaRequest struct{Position int `json:"position"`;Checked bool `json:"checked"`;Summary string `json:"summary"`;Description *string `json:"description"`;PresentedByID *string `json:"presented_by_id"`}
func(h *Handler)CreateAgendaItem(w http.ResponseWriter,r *http.Request){m:=member(r);var req agendaRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Summary)==""{response.Fail(w,422,"summary is required",nil);return};id:=uuidv7.New();tag,err:=h.pool.Exec(r.Context(),`INSERT INTO agenda_items(id,meeting_id,position,checked,summary,description,presented_by_id) SELECT $1,mt.id,$2,$3,$4,$5,$6 FROM meetings mt JOIN groups g ON g.id=mt.group_id WHERE mt.id=$7 AND g.company_id=$8`,id,req.Position,req.Checked,strings.TrimSpace(req.Summary),req.Description,req.PresentedByID,chi.URLParam(r,"meetingId"),m.CompanyID);if err!=nil{response.Fail(w,500,"create agenda item failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Meeting not found",nil);return};response.Created(w,"Agenda item created",map[string]interface{}{"id":id,"position":req.Position,"checked":req.Checked,"summary":req.Summary,"description":req.Description,"presented_by_id":req.PresentedByID})}
func(h *Handler)UpdateAgendaItem(w http.ResponseWriter,r *http.Request){m:=member(r);var req agendaRequest;if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Summary)==""{response.Fail(w,422,"summary is required",nil);return};tag,err:=h.pool.Exec(r.Context(),`UPDATE agenda_items a SET position=$1,checked=$2,summary=$3,description=$4,presented_by_id=$5,updated_at=now() FROM meetings mt,groups g WHERE a.id=$6 AND a.meeting_id=mt.id AND mt.group_id=g.id AND g.company_id=$7`,req.Position,req.Checked,strings.TrimSpace(req.Summary),req.Description,req.PresentedByID,chi.URLParam(r,"agendaItemId"),m.CompanyID);if err!=nil{response.Fail(w,500,"update agenda item failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Agenda item not found",nil);return};response.OK(w,"Agenda item updated",nil)}
func(h *Handler)DeleteAgendaItem(w http.ResponseWriter,r *http.Request){m:=member(r);tag,err:=h.pool.Exec(r.Context(),`DELETE FROM agenda_items a USING meetings mt,groups g WHERE a.id=$1 AND a.meeting_id=mt.id AND mt.group_id=g.id AND g.company_id=$2`,chi.URLParam(r,"agendaItemId"),m.CompanyID);deleted(w,tag.RowsAffected(),err,"Agenda item")}
func(h *Handler)CreateDecision(w http.ResponseWriter,r *http.Request){m:=member(r);var req struct{Description string `json:"description"`};if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Description)==""{response.Fail(w,422,"description is required",nil);return};id:=uuidv7.New();tag,err:=h.pool.Exec(r.Context(),`INSERT INTO meeting_decisions(id,agenda_item_id,description) SELECT $1,a.id,$2 FROM agenda_items a JOIN meetings mt ON mt.id=a.meeting_id JOIN groups g ON g.id=mt.group_id WHERE a.id=$3 AND g.company_id=$4`,id,strings.TrimSpace(req.Description),chi.URLParam(r,"agendaItemId"),m.CompanyID);if err!=nil{response.Fail(w,500,"create decision failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Agenda item not found",nil);return};response.Created(w,"Decision created",map[string]interface{}{"id":id,"description":req.Description})}
func(h *Handler)UpdateDecision(w http.ResponseWriter,r *http.Request){m:=member(r);var req struct{Description string `json:"description"`};if json.NewDecoder(r.Body).Decode(&req)!=nil||strings.TrimSpace(req.Description)==""{response.Fail(w,422,"description is required",nil);return};tag,err:=h.pool.Exec(r.Context(),`UPDATE meeting_decisions d SET description=$1,updated_at=now() FROM agenda_items a,meetings mt,groups g WHERE d.id=$2 AND d.agenda_item_id=a.id AND a.meeting_id=mt.id AND mt.group_id=g.id AND g.company_id=$3`,strings.TrimSpace(req.Description),chi.URLParam(r,"decisionId"),m.CompanyID);if err!=nil{response.Fail(w,500,"update decision failed",err.Error());return};if tag.RowsAffected()==0{response.Fail(w,404,"Decision not found",nil);return};response.OK(w,"Decision updated",nil)}
func(h *Handler)DeleteDecision(w http.ResponseWriter,r *http.Request){m:=member(r);tag,err:=h.pool.Exec(r.Context(),`DELETE FROM meeting_decisions d USING agenda_items a,meetings mt,groups g WHERE d.id=$1 AND d.agenda_item_id=a.id AND a.meeting_id=mt.id AND mt.group_id=g.id AND g.company_id=$2`,chi.URLParam(r,"decisionId"),m.CompanyID);deleted(w,tag.RowsAffected(),err,"Decision")}

func parseDate(raw *string)(*time.Time,bool){if raw==nil||*raw==""{return nil,true};day,err:=time.Parse("2006-01-02",*raw);return &day,err==nil}
func meetingPayload(id,groupID string,happened bool,happenedAt *time.Time,created time.Time)map[string]interface{}{var day interface{};if happenedAt!=nil{day=happenedAt.Format("2006-01-02")};return map[string]interface{}{"id":id,"group_id":groupID,"happened":happened,"happened_at":day,"created_at":created.UTC().Format(time.RFC3339)}}
func(h *Handler)attendees(r *http.Request,meetingID string)([]map[string]interface{},error){rows,err:=h.pool.Query(r.Context(),`SELECT e.id,e.first_name,e.last_name,em.was_a_guest,em.attended FROM employee_meeting em JOIN employees e ON e.id=em.employee_id WHERE em.meeting_id=$1`,meetingID);if err!=nil{return nil,err};defer rows.Close();out:=[]map[string]interface{}{};for rows.Next(){var id,first,last string;var guest,attended bool;if err:=rows.Scan(&id,&first,&last,&guest,&attended);err!=nil{return nil,err};out=append(out,map[string]interface{}{"employee_id":id,"first_name":first,"last_name":last,"was_a_guest":guest,"attended":attended})};return out,nil}
func(h *Handler)agenda(r *http.Request,meetingID string)([]map[string]interface{},error){rows,err:=h.pool.Query(r.Context(),`SELECT a.id,a.position,a.checked,a.summary,a.description,a.presented_by_id,d.id,d.description FROM agenda_items a LEFT JOIN meeting_decisions d ON d.agenda_item_id=a.id WHERE a.meeting_id=$1 ORDER BY a.position,a.id,d.id`,meetingID);if err!=nil{return nil,err};defer rows.Close();out:=[]map[string]interface{}{};index:=map[string]int{};for rows.Next(){var id,summary string;var pos int;var checked bool;var description,presenter,did,decision *string;if err:=rows.Scan(&id,&pos,&checked,&summary,&description,&presenter,&did,&decision);err!=nil{return nil,err};i,ok:=index[id];if !ok{i=len(out);index[id]=i;out=append(out,map[string]interface{}{"id":id,"position":pos,"checked":checked,"summary":summary,"description":description,"presented_by_id":presenter,"decisions":[]map[string]interface{}{}})};if did!=nil{items:=out[i]["decisions"].([]map[string]interface{});out[i]["decisions"]=append(items,map[string]interface{}{"id":*did,"description":decision})}};return out,nil}
