// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package companydb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Company module SQLC query sources.
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	ExistsCompanyByJoinCode(ctx context.Context, codeToJoinCompany string) (bool, error)
	ExistsCompanyBySlug(ctx context.Context, slug string) (bool, error)
	ExistsCompanyBySlugExceptID(ctx context.Context, arg ExistsCompanyBySlugExceptIDParams) (bool, error)
	GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error)
	GetCompanyByJoinCode(ctx context.Context, codeToJoinCompany string) (Company, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
}

var _ Querier = (*Queries)(nil)
