// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package companydb

import (
	"context"

	"github.com/google/uuid"
)

const createCompany = `-- name: CreateCompany :one

INSERT INTO companies (id, name, slug, currency, code_to_join_company, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, name, slug, currency, code_to_join_company, created_at, updated_at
`

type CreateCompanyParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Slug              string    `json:"slug"`
	Currency          string    `json:"currency"`
	CodeToJoinCompany string    `json:"code_to_join_company"`
}

// Company module SQLC query sources.
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Currency,
		arg.CodeToJoinCompany,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Currency,
		&i.CodeToJoinCompany,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsCompanyByJoinCode = `-- name: ExistsCompanyByJoinCode :one
SELECT EXISTS(SELECT 1 FROM companies WHERE code_to_join_company = $1) AS exists
`

func (q *Queries) ExistsCompanyByJoinCode(ctx context.Context, codeToJoinCompany string) (bool, error) {
	row := q.db.QueryRow(ctx, existsCompanyByJoinCode, codeToJoinCompany)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsCompanyBySlug = `-- name: ExistsCompanyBySlug :one
SELECT EXISTS(SELECT 1 FROM companies WHERE slug = $1) AS exists
`

func (q *Queries) ExistsCompanyBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, existsCompanyBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsCompanyBySlugExceptID = `-- name: ExistsCompanyBySlugExceptID :one
SELECT EXISTS(SELECT 1 FROM companies WHERE slug = $1 AND id != $2) AS exists
`

type ExistsCompanyBySlugExceptIDParams struct {
	Slug string    `json:"slug"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) ExistsCompanyBySlugExceptID(ctx context.Context, arg ExistsCompanyBySlugExceptIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsCompanyBySlugExceptID, arg.Slug, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, slug, currency, code_to_join_company, created_at, updated_at
FROM companies
WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Currency,
		&i.CodeToJoinCompany,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyByJoinCode = `-- name: GetCompanyByJoinCode :one
SELECT id, name, slug, currency, code_to_join_company, created_at, updated_at
FROM companies
WHERE code_to_join_company = $1
`

func (q *Queries) GetCompanyByJoinCode(ctx context.Context, codeToJoinCompany string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByJoinCode, codeToJoinCompany)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Currency,
		&i.CodeToJoinCompany,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $2, slug = $3, currency = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, currency, code_to_join_company, created_at, updated_at
`

type UpdateCompanyParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
	Currency string    `json:"currency"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Currency,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Currency,
		&i.CodeToJoinCompany,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
