// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package employeedb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignEmployeeRole(ctx context.Context, arg AssignEmployeeRoleParams) error
	ClaimEmployeeInvitation(ctx context.Context, arg ClaimEmployeeInvitationParams) (Employee, error)
	ClearEmployeeRoles(ctx context.Context, employeeID uuid.UUID) error
	// Employee module SQLC query sources: positions, employee_statuses,
	// employees, employee_roles (+ read-only lookups against the shared
	// companies/roles/permissions tables the employee module needs).
	CompanyExists(ctx context.Context, id uuid.UUID) (bool, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateEmployeeStatus(ctx context.Context, arg CreateEmployeeStatusParams) (EmployeeStatus, error)
	CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error)
	DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) error
	DeleteEmployeeStatus(ctx context.Context, arg DeleteEmployeeStatusParams) error
	DeletePosition(ctx context.Context, arg DeletePositionParams) error
	ExistsEmployeeByCompanyAndUserExceptID(ctx context.Context, arg ExistsEmployeeByCompanyAndUserExceptIDParams) (bool, error)
	GetEmployeeByCompanyAndUser(ctx context.Context, arg GetEmployeeByCompanyAndUserParams) (Employee, error)
	GetEmployeeByIDInCompany(ctx context.Context, arg GetEmployeeByIDInCompanyParams) (Employee, error)
	GetEmployeeByInvitationLink(ctx context.Context, invitationLink *uuid.UUID) (Employee, error)
	GetEmployeeStatusByIDInCompany(ctx context.Context, arg GetEmployeeStatusByIDInCompanyParams) (EmployeeStatus, error)
	GetPositionByIDInCompany(ctx context.Context, arg GetPositionByIDInCompanyParams) (Position, error)
	GetRoleIDByName(ctx context.Context, name string) (uuid.UUID, error)
	GetUnclaimedEmployeeByCompanyAndEmail(ctx context.Context, arg GetUnclaimedEmployeeByCompanyAndEmailParams) (Employee, error)
	ListEmployeePermissionNames(ctx context.Context, employeeID uuid.UUID) ([]string, error)
	ListEmployeeRoleNames(ctx context.Context, employeeID uuid.UUID) ([]string, error)
	ListEmployeeStatusesByCompany(ctx context.Context, companyID uuid.UUID) ([]EmployeeStatus, error)
	ListEmployeesByCompany(ctx context.Context, companyID uuid.UUID) ([]Employee, error)
	ListPositionsByCompany(ctx context.Context, companyID uuid.UUID) ([]Position, error)
	SetEmployeeInvitation(ctx context.Context, arg SetEmployeeInvitationParams) (Employee, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	UpdateEmployeeStatus(ctx context.Context, arg UpdateEmployeeStatusParams) (EmployeeStatus, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error)
}

var _ Querier = (*Queries)(nil)
