// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package employeedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignEmployeeRole = `-- name: AssignEmployeeRole :exec
INSERT INTO employee_roles (employee_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignEmployeeRoleParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	RoleID     uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignEmployeeRole(ctx context.Context, arg AssignEmployeeRoleParams) error {
	_, err := q.db.Exec(ctx, assignEmployeeRole, arg.EmployeeID, arg.RoleID)
	return err
}

const claimEmployeeInvitation = `-- name: ClaimEmployeeInvitation :one
UPDATE employees
SET user_id = $2, invitation_used_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
`

type ClaimEmployeeInvitationParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) ClaimEmployeeInvitation(ctx context.Context, arg ClaimEmployeeInvitationParams) (Employee, error) {
	row := q.db.QueryRow(ctx, claimEmployeeInvitation, arg.ID, arg.UserID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HiredAt,
		&i.PositionID,
		&i.EmployeeStatusID,
		&i.InvitationLink,
		&i.InvitationUsedAt,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearEmployeeRoles = `-- name: ClearEmployeeRoles :exec
DELETE FROM employee_roles WHERE employee_id = $1
`

func (q *Queries) ClearEmployeeRoles(ctx context.Context, employeeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearEmployeeRoles, employeeID)
	return err
}

const companyExists = `-- name: CompanyExists :one

SELECT EXISTS(SELECT 1 FROM companies WHERE id = $1) AS exists
`

// Employee module SQLC query sources: positions, employee_statuses,
// employees, employee_roles (+ read-only lookups against the shared
// companies/roles/permissions tables the employee module needs).
func (q *Queries) CompanyExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, companyExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, locked, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), now())
RETURNING id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
`

type CreateEmployeeParams struct {
	ID               uuid.UUID  `json:"id"`
	CompanyID        uuid.UUID  `json:"company_id"`
	UserID           *uuid.UUID `json:"user_id"`
	Email            string     `json:"email"`
	FirstName        string     `json:"first_name"`
	LastName         string     `json:"last_name"`
	HiredAt          *time.Time `json:"hired_at"`
	PositionID       *uuid.UUID `json:"position_id"`
	EmployeeStatusID *uuid.UUID `json:"employee_status_id"`
	Locked           bool       `json:"locked"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.HiredAt,
		arg.PositionID,
		arg.EmployeeStatusID,
		arg.Locked,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HiredAt,
		&i.PositionID,
		&i.EmployeeStatusID,
		&i.InvitationLink,
		&i.InvitationUsedAt,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmployeeStatus = `-- name: CreateEmployeeStatus :one
INSERT INTO employee_statuses (id, company_id, name, type, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, company_id, name, type, created_at, updated_at
`

type CreateEmployeeStatusParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
}

func (q *Queries) CreateEmployeeStatus(ctx context.Context, arg CreateEmployeeStatusParams) (EmployeeStatus, error) {
	row := q.db.QueryRow(ctx, createEmployeeStatus,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Type,
	)
	var i EmployeeStatus
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (id, company_id, title, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
RETURNING id, company_id, title, created_at, updated_at
`

type CreatePositionParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Title     string    `json:"title"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition, arg.ID, arg.CompanyID, arg.Title)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees WHERE id = $1 AND company_id = $2
`

type DeleteEmployeeParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) error {
	_, err := q.db.Exec(ctx, deleteEmployee, arg.ID, arg.CompanyID)
	return err
}

const deleteEmployeeStatus = `-- name: DeleteEmployeeStatus :exec
DELETE FROM employee_statuses WHERE id = $1 AND company_id = $2
`

type DeleteEmployeeStatusParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteEmployeeStatus(ctx context.Context, arg DeleteEmployeeStatusParams) error {
	_, err := q.db.Exec(ctx, deleteEmployeeStatus, arg.ID, arg.CompanyID)
	return err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions WHERE id = $1 AND company_id = $2
`

type DeletePositionParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) error {
	_, err := q.db.Exec(ctx, deletePosition, arg.ID, arg.CompanyID)
	return err
}

const existsEmployeeByCompanyAndUserExceptID = `-- name: ExistsEmployeeByCompanyAndUserExceptID :one
SELECT EXISTS(
    SELECT 1 FROM employees WHERE company_id = $1 AND user_id = $2 AND id != $3
) AS exists
`

type ExistsEmployeeByCompanyAndUserExceptIDParams struct {
	CompanyID uuid.UUID  `json:"company_id"`
	UserID    *uuid.UUID `json:"user_id"`
	ID        uuid.UUID  `json:"id"`
}

func (q *Queries) ExistsEmployeeByCompanyAndUserExceptID(ctx context.Context, arg ExistsEmployeeByCompanyAndUserExceptIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsEmployeeByCompanyAndUserExceptID, arg.CompanyID, arg.UserID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getEmployeeByCompanyAndUser = `-- name: GetEmployeeByCompanyAndUser :one
SELECT id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
FROM employees
WHERE company_id = $1 AND user_id = $2
`

type GetEmployeeByCompanyAndUserParams struct {
	CompanyID uuid.UUID  `json:"company_id"`
	UserID    *uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEmployeeByCompanyAndUser(ctx context.Context, arg GetEmployeeByCompanyAndUserParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByCompanyAndUser, arg.CompanyID, arg.UserID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HiredAt,
		&i.PositionID,
		&i.EmployeeStatusID,
		&i.InvitationLink,
		&i.InvitationUsedAt,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByIDInCompany = `-- name: GetEmployeeByIDInCompany :one
SELECT id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
FROM employees
WHERE id = $1 AND company_id = $2
`

type GetEmployeeByIDInCompanyParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetEmployeeByIDInCompany(ctx context.Context, arg GetEmployeeByIDInCompanyParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByIDInCompany, arg.ID, arg.CompanyID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HiredAt,
		&i.PositionID,
		&i.EmployeeStatusID,
		&i.InvitationLink,
		&i.InvitationUsedAt,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByInvitationLink = `-- name: GetEmployeeByInvitationLink :one
SELECT id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
FROM employees
WHERE invitation_link = $1
`

func (q *Queries) GetEmployeeByInvitationLink(ctx context.Context, invitationLink *uuid.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByInvitationLink, invitationLink)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HiredAt,
		&i.PositionID,
		&i.EmployeeStatusID,
		&i.InvitationLink,
		&i.InvitationUsedAt,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeStatusByIDInCompany = `-- name: GetEmployeeStatusByIDInCompany :one
SELECT id, company_id, name, type, created_at, updated_at
FROM employee_statuses
WHERE id = $1 AND company_id = $2
`

type GetEmployeeStatusByIDInCompanyParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetEmployeeStatusByIDInCompany(ctx context.Context, arg GetEmployeeStatusByIDInCompanyParams) (EmployeeStatus, error) {
	row := q.db.QueryRow(ctx, getEmployeeStatusByIDInCompany, arg.ID, arg.CompanyID)
	var i EmployeeStatus
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionByIDInCompany = `-- name: GetPositionByIDInCompany :one
SELECT id, company_id, title, created_at, updated_at
FROM positions
WHERE id = $1 AND company_id = $2
`

type GetPositionByIDInCompanyParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetPositionByIDInCompany(ctx context.Context, arg GetPositionByIDInCompanyParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByIDInCompany, arg.ID, arg.CompanyID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleIDByName = `-- name: GetRoleIDByName :one
SELECT id FROM roles WHERE name = $1
`

func (q *Queries) GetRoleIDByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRoleIDByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUnclaimedEmployeeByCompanyAndEmail = `-- name: GetUnclaimedEmployeeByCompanyAndEmail :one
SELECT id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
FROM employees
WHERE company_id = $1 AND email = $2 AND user_id IS NULL
`

type GetUnclaimedEmployeeByCompanyAndEmailParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Email     string    `json:"email"`
}

func (q *Queries) GetUnclaimedEmployeeByCompanyAndEmail(ctx context.Context, arg GetUnclaimedEmployeeByCompanyAndEmailParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getUnclaimedEmployeeByCompanyAndEmail, arg.CompanyID, arg.Email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HiredAt,
		&i.PositionID,
		&i.EmployeeStatusID,
		&i.InvitationLink,
		&i.InvitationUsedAt,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployeePermissionNames = `-- name: ListEmployeePermissionNames :many
SELECT DISTINCT p.name
FROM employee_roles er
JOIN role_permissions rp ON rp.role_id = er.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE er.employee_id = $1
`

func (q *Queries) ListEmployeePermissionNames(ctx context.Context, employeeID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEmployeePermissionNames, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeRoleNames = `-- name: ListEmployeeRoleNames :many
SELECT r.name
FROM employee_roles er
JOIN roles r ON r.id = er.role_id
WHERE er.employee_id = $1
ORDER BY r.name
`

func (q *Queries) ListEmployeeRoleNames(ctx context.Context, employeeID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEmployeeRoleNames, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeStatusesByCompany = `-- name: ListEmployeeStatusesByCompany :many
SELECT id, company_id, name, type, created_at, updated_at
FROM employee_statuses
WHERE company_id = $1
ORDER BY name
`

func (q *Queries) ListEmployeeStatusesByCompany(ctx context.Context, companyID uuid.UUID) ([]EmployeeStatus, error) {
	rows, err := q.db.Query(ctx, listEmployeeStatusesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeStatus
	for rows.Next() {
		var i EmployeeStatus
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByCompany = `-- name: ListEmployeesByCompany :many
SELECT id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
FROM employees
WHERE company_id = $1
ORDER BY last_name, first_name
`

func (q *Queries) ListEmployeesByCompany(ctx context.Context, companyID uuid.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.HiredAt,
			&i.PositionID,
			&i.EmployeeStatusID,
			&i.InvitationLink,
			&i.InvitationUsedAt,
			&i.Locked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByCompany = `-- name: ListPositionsByCompany :many
SELECT id, company_id, title, created_at, updated_at
FROM positions
WHERE company_id = $1
ORDER BY title
`

func (q *Queries) ListPositionsByCompany(ctx context.Context, companyID uuid.UUID) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmployeeInvitation = `-- name: SetEmployeeInvitation :one
UPDATE employees
SET invitation_link = $2, invitation_used_at = NULL, updated_at = now()
WHERE id = $1
RETURNING id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
`

type SetEmployeeInvitationParams struct {
	ID             uuid.UUID  `json:"id"`
	InvitationLink *uuid.UUID `json:"invitation_link"`
}

func (q *Queries) SetEmployeeInvitation(ctx context.Context, arg SetEmployeeInvitationParams) (Employee, error) {
	row := q.db.QueryRow(ctx, setEmployeeInvitation, arg.ID, arg.InvitationLink)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HiredAt,
		&i.PositionID,
		&i.EmployeeStatusID,
		&i.InvitationLink,
		&i.InvitationUsedAt,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET email = $3, first_name = $4, last_name = $5, hired_at = $6,
    position_id = $7, employee_status_id = $8, locked = $9, updated_at = now()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, user_id, email, first_name, last_name, hired_at,
    position_id, employee_status_id, invitation_link, invitation_used_at,
    locked, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID               uuid.UUID  `json:"id"`
	CompanyID        uuid.UUID  `json:"company_id"`
	Email            string     `json:"email"`
	FirstName        string     `json:"first_name"`
	LastName         string     `json:"last_name"`
	HiredAt          *time.Time `json:"hired_at"`
	PositionID       *uuid.UUID `json:"position_id"`
	EmployeeStatusID *uuid.UUID `json:"employee_status_id"`
	Locked           bool       `json:"locked"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.CompanyID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.HiredAt,
		arg.PositionID,
		arg.EmployeeStatusID,
		arg.Locked,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.HiredAt,
		&i.PositionID,
		&i.EmployeeStatusID,
		&i.InvitationLink,
		&i.InvitationUsedAt,
		&i.Locked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployeeStatus = `-- name: UpdateEmployeeStatus :one
UPDATE employee_statuses
SET name = $3, type = $4, updated_at = now()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, type, created_at, updated_at
`

type UpdateEmployeeStatusParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
}

func (q *Queries) UpdateEmployeeStatus(ctx context.Context, arg UpdateEmployeeStatusParams) (EmployeeStatus, error) {
	row := q.db.QueryRow(ctx, updateEmployeeStatus,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Type,
	)
	var i EmployeeStatus
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET title = $3, updated_at = now()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, title, created_at, updated_at
`

type UpdatePositionParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Title     string    `json:"title"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition, arg.ID, arg.CompanyID, arg.Title)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
