// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package coredb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// Core SQLC query sources: users, refresh_tokens.
	// Roles/permissions/employee_roles are queried from the employee module's
	// own SQL (sql/employee/queries.sql) since it owns the RBAC-check use case;
	// these tables still physically live in the shared Postgres database.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRefreshTokenByJTI(ctx context.Context, jti uuid.UUID) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	RevokeRefreshTokenByJTI(ctx context.Context, jti uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
