// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package coredb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, jti, expires_at, created_at)
VALUES ($1, $2, $3, $4, now())
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Jti       uuid.UUID `json:"jti"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.Jti,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, name, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, email, name, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
}

// Core SQLC query sources: users, refresh_tokens.
// Roles/permissions/employee_roles are queried from the employee module's
// own SQL (sql/employee/queries.sql) since it owns the RBAC-check use case;
// these tables still physically live in the shared Postgres database.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenByJTI = `-- name: GetRefreshTokenByJTI :one
SELECT id, user_id, jti, expires_at, revoked_at, created_at
FROM refresh_tokens
WHERE jti = $1
`

func (q *Queries) GetRefreshTokenByJTI(ctx context.Context, jti uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByJTI, jti)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeRefreshTokenByJTI = `-- name: RevokeRefreshTokenByJTI :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE jti = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByJTI(ctx context.Context, jti uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByJTI, jti)
	return err
}
